# Generated by Django 2.1 on 2019-06-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apply_experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.CharField(max_length=20, verbose_name='实验室名称')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_experiments.Experiment', verbose_name='审核通过了的实验项目')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
