# Generated by Django 2.1 on 2019-07-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_manage', '0003_auto_20190724_1649'),
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='助理姓名')),
                ('account', models.CharField(max_length=100, verbose_name='账号')),
                ('password', models.CharField(default='123456', max_length=18, verbose_name='登录密码')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.Teacher', verbose_name='协助的教师')),
            ],
            options={
                'db_table': 'assistant',
            },
        ),
    ]
