# Generated by Django 2.1 on 2019-06-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班级名称')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('classes', models.ManyToManyField(to='super_manage.Classes', verbose_name='授课班级')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='系名称')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='年级名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.Department', verbose_name='所属系')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学院名称')),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学校名称')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='校区名称')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.School', verbose_name='所属学校')),
            ],
            options={
                'db_table': 'school_area',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('account', models.IntegerField(verbose_name='登录账号，应为教师工号')),
                ('password', models.CharField(default='123456', max_length=18, verbose_name='登录密码')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机号码（用于找回密码，非必填）')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.Department', verbose_name='所属系')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TotalRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consume_requirements', models.CharField(blank=True, max_length=100, null=True, verbose_name='总体耗材需求')),
                ('total_system_requirements', models.CharField(blank=True, max_length=100, null=True, verbose_name='总体系统需求')),
                ('total_soft_requirements', models.CharField(blank=True, max_length=100, null=True, verbose_name='总体软件需求')),
                ('teaching_materials', models.CharField(blank=True, max_length=200, null=True, verbose_name='总体软件需求')),
            ],
            options={
                'db_table': 'total_requirements',
            },
        ),
        migrations.AddField(
            model_name='institute',
            name='school_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.SchoolArea', verbose_name='所属校区'),
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.Institute', verbose_name='所属学院'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='super_manage.Teacher', verbose_name='授课老师'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.TotalRequirements', verbose_name='总体实验需求'),
        ),
        migrations.AddField(
            model_name='classes',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_manage.Grade', verbose_name='所属年级'),
        ),
    ]
