# Generated by Django 2.1 on 2019-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='account',
            field=models.CharField(max_length=100, verbose_name='登录账号，应为教师工号'),
        ),
    ]
