# Generated by Django 2.1 on 2019-07-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_manage', '0002_auto_20190724_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码（用于找回密码，非必填）'),
        ),
    ]
