# Generated by Django 2.1 on 2019-07-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_manage', '0003_auto_20190724_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='super_manage.TotalRequirements', verbose_name='总体实验需求'),
        ),
    ]
