# Generated by Django 2.1 on 2019-08-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_manage', '0004_auto_20190726_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsattribute',
            name='labs',
        ),
        migrations.AddField(
            model_name='labs',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_manage.LabsAttribute', verbose_name='实验室属性'),
        ),
    ]
